apiVersion: v1
kind: PersistentVolume

metadata:
  name: minishop-pv

spec:
  capacity:
    storage: 2Gi

  volumeMode: Filesystem

  accessModes:
  - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: manual

  hostPath:
    path: /data/minishop