apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: minishop-pvc
  namespace: minishop-dev

spec:
  accessModes:
  - ReadWriteOnce

  storageClassName: manual

  resources:
    requests:
      storage: 2Gi