name: Deployment

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main

jobs:
  Deployment:
    runs-on: [self-hosted, windows, x64]

    steps:
      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      # Verify Node Version
      - name: Check Node Version
        run: node -v

      # Clean Old Dependencies
      - name: Clean Old Dependencies
        shell: powershell
        run: |
          if (Test-Path node_modules) {
            Remove-Item -Recurse -Force node_modules
          }

          if (Test-Path package-lock.json) {
            Remove-Item -Force package-lock.json
          }

      # Install Dependencies
      - name: Install Dependencies
        run: |
          npm install
          npm install react-scripts@5.0.1 --save

      # Verify react-scripts
      - name: Verify React Scripts
        run: npm list react-scripts

      # SonarQube Scan
      - name: SonarQube Scan
        continue-on-error: true
        shell: powershell
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner `
            "-Dsonar.projectKey=minishopapp" `
            "-Dsonar.projectName=minishopapp" `
            "-Dsonar.sources=src" `
            "-Dsonar.sourceEncoding=UTF-8" `
            "-Dsonar.host.url=$env:SONAR_HOST_URL" `
            "-Dsonar.token=$env:SONAR_TOKEN" `
            "-Dsonar.javascript.lcov.reportPaths=coverage/lcov.info" `
            "-Dsonar.qualitygate.wait=true"

      # OWASP Dependency Check
      - name: OWASP Dependency Check
        shell: powershell
        run: |
          C:\dependency-check\bin\dependency-check.bat `
            --project "minishopapp" `
            --scan "." `
            --format "HTML" `
            --out "reports" `
            --data "C:\dependency-check\data" `
            --disableYarnAudit `
            --disableAssembly `
            --disableMSBuild `
            --failOnCVSS 11

      # Upload OWASP Report
      - name: Upload OWASP Report
        uses: actions/upload-artifact@v4
        with:
          name: OWASP-Report
          path: reports

      # Build React App
      - name: Build App
        run: npm run build