name: Deployment

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main

jobs:
  Deployment:
    runs-on: [self-hosted, windows, x64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Check Node Version
        run: node -v

      - name: Install Dependencies
        run: npm install

      # SonarQube Scan
      - name: SonarQube Scan
        continue-on-error: true
        shell: powershell
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner `
            "-Dsonar.projectKey=minishopapp" `
            "-Dsonar.projectName=minishopapp" `
            "-Dsonar.sources=src" `
            "-Dsonar.sourceEncoding=UTF-8" `
            "-Dsonar.host.url=$env:SONAR_HOST_URL" `
            "-Dsonar.token=$env:SONAR_TOKEN" `
            "-Dsonar.javascript.lcov.reportPaths=coverage/lcov.info" `
            "-Dsonar.qualitygate.wait=true"

      # OWASP Dependency Check
      - name: OWASP Dependency Check
        shell: powershell
        run: |
          C:\dependency-check\bin\dependency-check.bat `
            --project "minishopapp" `
            --scan "." `
            --format "HTML" `
            --out "reports" `
            --failOnCVSS 7

      # Upload OWASP Report
      - name: Upload OWASP Report
        uses: actions/upload-artifact@v4
        with:
          name: OWASP-Report
          path: reports

      # Build App
      - name: Build App
        run: npm run build