name: Deployment

on:
  push:
    branches:
      - main

jobs:
  Deployment:
    runs-on: [self-hosted, windows, x64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: SonarQube Scan
        shell: powershell
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner `
            -Dsonar.projectKey=minishopapp `
            -Dsonar.projectName=minishopapp `
            -Dsonar.sources=src `
            -Dsonar.sourceEncoding=UTF-8 `
            -Dsonar.host.url=$env:SONAR_HOST_URL `
            -Dsonar.token=$env:SONAR_TOKEN

      - name: Build App
        run: npm run build